modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="exnihilonatureminerals"
version="1.0.0"
displayName="无中生有：传承-natureminerals扩展"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="David, MCreator"

[[dependencies.exnihilonatureminerals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




